name = "a1lms"
compatibility_date = "2025-09-27"
main = "worker.js"

[observability]
enabled = true

[assets]
directory = "."
binding = "ASSETS"

[build]
command = "npm run build"
output_dir = "."

[[kv_namespaces]]
binding = "DEVICE_SESSIONS"
id = "7a9d353a216f4672a4dae0120f70b3fb"


